name: Release Bookget (Multi-Arch)

on:
  push:
    tags: ["v*"]  # 推送 v1.0.0 这样的标签时触发

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]  # 同时编译 x86_64 和 ARM64
        go: ["1.23"]
        # 排除 Windows 上的 ARM64（Windows ARM 支持较少）
        exclude:
          - os: windows-latest
            arch: arm64
        # 为不同平台设置可执行文件后缀
        include:
          - os: ubuntu-latest
            arch: amd64
            suffix: ""
            output_dir: "linux-amd64"
          - os: ubuntu-latest
            arch: arm64
            suffix: "-arm64"
            output_dir: "linux-arm64"
          - os: macos-latest
            arch: amd64
            suffix: ""
            output_dir: "darwin-amd64"
          - os: macos-latest
            arch: arm64
            suffix: "-arm64"
            output_dir: "darwin-arm64"
          - os: windows-latest
            arch: amd64
            suffix: ".exe"
            output_dir: "windows-amd64"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Build bookget
        run: |
          # 设置输出文件名
          OUTPUT="bookget${{ matrix.suffix }}"
          
          # 编译命令
          GOOS=${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'darwin' || 'linux' }} \
          GOARCH=${{ matrix.arch }} \
          CGO_ENABLED=0 \  # 禁用 CGO 以获得完全静态二进制文件
          go build -o "dist/${{ matrix.output_dir }}/$OUTPUT" ./cmd/bookget

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bookget-${{ matrix.output_dir }}
          path: dist/${{ matrix.output_dir }}/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Bookget ${{ github.ref_name }}"
          body: |
            Multi-architecture release including:
            - Linux (amd64/arm64)
            - macOS (amd64/arm64)
            - Windows (amd64)
          files: |
            dist/bookget-linux-amd64/bookget
            dist/bookget-linux-arm64/bookget-arm64
            dist/bookget-darwin-amd64/bookget
            dist/bookget-darwin-arm64/bookget-arm64
            dist/bookget-windows-amd64/bookget.exe