name: Release Bookget

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - linux-amd64
          - linux-arm64
          - darwin-amd64
          - darwin-arm64
          - windows-amd64
    runs-on: ${{
      contains(matrix.platform, 'linux') && 'ubuntu-latest' ||
      contains(matrix.platform, 'darwin') && 'macos-latest' ||
      'windows-latest'}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Make (Windows)
        if: runner.os == 'Windows'
        run: choco install make -y

      - name: Build
        run: |
          make ${{ matrix.platform }}

      - name: Verify artifacts
        run: ls -R dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookget-${{ matrix.platform }}
          path: dist/${{ matrix.platform }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须添加这个权限
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Bookget ${{ github.ref_name }}"
          body: "Multi-architecture release"
          files: |
            dist/bookget-linux-amd64/bookget
            dist/bookget-linux-arm64/bookget
            dist/bookget-darwin-amd64/bookget
            dist/bookget-darwin-arm64/bookget
            dist/bookget-windows-amd64/bookget.exe