name: Release Bookget (Multi-Arch)

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            arch: amd64
            suffix: ""
            output_dir: "linux-amd64"
            shell: bash
          - os: ubuntu-latest
            goos: linux
            arch: arm64
            suffix: "-arm64"
            output_dir: "linux-arm64"
            shell: bash
          - os: macos-latest
            goos: darwin
            arch: amd64
            suffix: ""
            output_dir: "darwin-amd64"
            shell: bash
          - os: macos-latest
            goos: darwin
            arch: arm64
            suffix: "-arm64"
            output_dir: "darwin-arm64"
            shell: bash
          - os: windows-latest
            goos: windows
            arch: amd64
            suffix: ".exe"
            output_dir: "windows-amd64"
            shell: pwsh
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build bookget
        shell: ${{ matrix.shell }}
        run: |
          if ("${{ matrix.os }}" -eq "windows-latest") {
            $env:GOOS="${{ matrix.goos }}"
            $env:GOARCH="${{ matrix.arch }}"
            $env:CGO_ENABLED="0"
            go build -o "dist/${{ matrix.output_dir }}/bookget${{ matrix.suffix }}" ./cmd/
          } else {
            export GOOS=${{ matrix.goos }}
            export GOARCH=${{ matrix.arch }}
            export CGO_ENABLED=0
            go build -o "dist/${{ matrix.output_dir }}/bookget${{ matrix.suffix }}" ./cmd/
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # 使用最新v4版本
        with:
          name: bookget-${{ matrix.output_dir }}
          path: dist/${{ matrix.output_dir }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4  # 使用最新v4版本
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Bookget ${{ github.ref_name }}"
          body: "Multi-architecture release"
          files: |
            dist/bookget-linux-amd64/bookget
            dist/bookget-linux-arm64/bookget
            dist/bookget-darwin-amd64/bookget
            dist/bookget-darwin-arm64/bookget
            dist/bookget-windows-amd64/bookget.exe